name: "Automated web UI tests with Cypress | $(Date:yyyyMMdd)$(Rev:.r)"

stages:
  - stage: tests_chrome
    displayName: "E2E tests on Chrome"
    jobs:
      - job: job_chrome
        displayName: "Run tests"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"

          - script: |
              npm run test
              npm run report
            displayName: "run tests"
