name: "Automated web UI tests with Cypress - $(Date:yyyyMMdd)$(Rev:.r)"

stages:
  - stage: tests_chrome
    displayName: "E2E tests on Chrome"
    jobs:
      - job: job_chrome
        displayName: "Run tests"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"

          - script: |
              npm install
            displayName: "Install dependencies"

          - script: |
              npm run test
            displayName: "Run tests"

          - script: |
              npm run report
            displayName: "Generate test reports"

          - task: PublishTestResults@2
            displayName: "Publish test results"
            condition: succeededOrFailed()
            inputs:
              testRunner: JUnit
              testResultsFiles: "**/results-*.xml"
              mergeTestResults: true
              testRunTitle: "Automated test run"
              publishRunAttachments: true

          - task: PublishPipelineArtifact@1
            displayName: "Publish test artifacts"
            inputs:
              targetPath: 'out'
              publishLocation: 'pipeline'
          
