image: cypress/browsers

pipelines:
  custom:
    run-tests:
      - step:
          name: run tests
          script:
            - npm install
            - npm run test
          after-script:
            - npm run report
          artifacts:
            - out/reports/**
