version: 2.1

jobs:
  run-tests:
    docker:
      - image: cypress/browsers
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: |
            npm run test
            npm run report
      - store_test_results:
          path: out/reports
      - store_artifacts:
          path: ./out

workflows:
  commit:
    jobs:
      - run-tests
