name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      testArg:
        description: 'Test argument'
        required: true
        default: 'Test value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: cypress-io/github-action@v1.16.1
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        with:
          files: out/reports/results-*.xml
          report_individual_runs: true
