name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      testArg:
        description: 'Test argument'
        required: true
        default: 'Test value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1.16.1
