name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      testArg:
        description: 'Test argument'
        required: true
        default: 'Test value'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
      - name: Generate reports
        if: always()
        run: npm run report
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2.2.0
        with:
          name: test-output
          path: out
      - name: Publish reports
        if: always()
        env:
          EMAIL: "github-actions-bot-noreply@noreply"
          USERNAME: "github-actions-bot"
        run: sh bin/publish-reports.sh
