name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      testArg:
        description: 'Test argument'
        required: true
        default: 'Test value'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node10.16.0-chrome77-ff71

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Generate reports
        if: always()
        run: npm run report
      - name: Publish artifacts
        if: always()
        uses: actions/upload-artifact@v2.2.0
        with:
          name: test-output
          path: out
      - name: Publish reports
          env:
            EMAIL: "github-actions-bot-noreply@noreply"
            USERNAME: "github-actions-bot"
          run: sh bin/publish-reports.sh
